name: Build and deploy personal website
on: [push]

jobs:
  build-and-deploy:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016, macos-latest]
        node-version: [12.x, 14.x]
        go: ['1.15']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2.3.1

    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.0.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Generate tex file for resume
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: |
        cd resume
        go run main.go

    - run: cd resume/resume && ls
    - name: TeX to pdf on Linux
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ./resume.tex
        latexmk_use_xelatex: true
    - name: Copy pdf to build directory
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
      run: |
        ls && cp resume.pdf ../../build/files/
        cd ../..
    
    - name: deploy
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
      uses: JamesIves/github-pages-deploy-action@3.5.8
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
